[package]
name = "data-enc"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
clap = { version = "4.5.35", features = ["derive"] }
indicatif = "0.17.11"
rayon = "1.10.0"
sha2 = "0.10.8"
walkdir = "2.5.0"
